---
namespace: trustwallet
name: blockchain
version: 0.5.14
readme: README.md
authors:
  - vorotech
description: |
  The Ansible Collection contains Trust Wallet's roles to manage blockchain nodes.
  Trust Wallet is a most trusted & secure crypto wallet.
license_file: LICENSE
tags:
  - blockbook
  - blockchain
  - cosmos
  - ethereum
  - nano
  - near
  - polygon
  - tron
dependencies:
  community.general: ">=4.2.0"
repository: https://github.com/trustwallet/ansible-collection-blockchain
issues: https://github.com/trustwallet/ansible-collection-blockchain/issues
homepage: https://trustwallet.com
build_ignore:
  - molecule
  - venv
  - "*.tar.gz"
