---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: "Include roles/polygon"
      ansible.builtin.include_role:
        name: roles/polygon
      vars:
        quicksync_mode: none
        eth_rpc_url: https://rpc.ankr.com/eth
