---
- name: "Prepare"
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: "Make sure python3 is installed"
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400
        pkg: python3

  roles:
    - role: telusdigital.unattended-upgrades

    - role: gantsign.golang
      golang_version: "1.18.1"
      golang_install_dir: /usr/local/go
