---
- name: Converge
  hosts: all

  tasks:
    - name: "Include roles/tron"
      ansible.builtin.include_role:
        name: roles/tron
      vars:
        #ansible_become: true
        quicksync_enabled: false
        tron_config_override: ./config/main_net_config.conf
