---
- name: "Prepare"
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: "Make sure python3 is installed"
      ansible.builtin.package:
        update_cache: true
        cache_valid_time: 86400
        name:
          - python3
          - python3-pip

  roles:
    - role: telusdigital.unattended-upgrades

    - role: lean_delivery.java
      java_distribution: corretto
      java_major_version: 8
