---
- name: Converge
  hosts: all
  tasks:
    - name: "Include roles/cosmos"
      ansible.builtin.include_role:
        name: roles/cosmos
      vars:
        ansible_become: true
        chain_name: "{{ lookup('env', 'COSMOS_CHAIN_NAME') }}"
        quicksync_mode: none
