---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: "Check COSMOS_CHAIN_NAME env var is set"
      ansible.builtin.assert:
        that: lookup('env', 'COSMOS_CHAIN_NAME') | default("") | length > 0

    - name: "Make sure python3 is installed"
      ansible.builtin.package:
        name: python3

  roles:
    - role: telusdigital.unattended-upgrades
    - role: gantsign.golang
      golang_version: "1.18.1"
      golang_install_dir: /usr/local/go
