---
- name: "Copy main net config"
  ansible.builtin.copy:
    content: "{{ lookup('file', tron_config_override | default('main_net_config.conf') ) }}"
    dest: "{{ data_dir }}/main_net_config.conf"
    owner: "{{ username }}"
    mode: "644"
  notify: restart_service
  become: true
