---
# <username> is the non-root user under which daemon will operate
username: polygon

# <home_dir> is a user home dir
home_dir: "/home/{{ username }}"

data_dir: "{{ home_dir }}"

# <bin_dir> is a binaries location dir, should be in the PATH.
bin_dir: /usr/local/bin

# <quicksync_mode> specifies Bor syncmode and snapshot type.
# Options are archive, full, pruned and none (sync bor from scratch)
quicksync_mode: pruned

# <quicksync_connection_num> is the maximum number of connections to the server for each download.
quicksync_connection_num: 5

# <quicksync_force> forces the chain data download step.
# Warning, the content of the data dir will be wiped.
# By default chain data will be downloaded only after chain init.
quicksync_force: false

# <quicksync_skip_download> skips steps to download quicksync chain data archive,
# assuming that the file has been already downloaded.
quicksync_skip_download: false

# <quicksync_tmp_dir> is the temporary dir to keep downloaded file.
# The aria2c package is utilized to speed up download process,
# but it requires double size to first download and then unpack data archive.
# In cloud environment the download dir often points to temporary mounted drive.
quicksync_tmp_dir: /tmp/quicksync

heimdall_dir: "{{ data_dir }}/.heimdalld"

heimdall_client_dir: "{{ data_dir }}/.heimdallcli"

# <heimdall_version>is the heimdall release version.
# See https://github.com/maticnetwork/heimdall/releases/
heimdall_version: v0.2.9

# <heimdall_moniker> is the custom username of your node
heimdall_moniker: moniker-1

heimdall_seeds: "f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:26656,4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656,2eadba4be3ce47ac8db0a3538cb923b57b41c927@35.199.4.13:26656,3b23b20017a6f348d329c102ddc0088f0a10a444@35.221.13.28:26656,25f5f65a09c56e9f1d2d90618aa70cd358aa68da@35.230.116.151:26656"

heimdall_daemon_name: heimdalld

heimdall_extra_run_args: ""

heimdall_rest_server_daemon_name: heimdalld-rest-server

heimdall_rest_server_extra_run_args: ""

# <heimdall_network> is the Heimdall service network, could be mainnet or mumbai (testnet)
heimdall_network: mainnet

heimdall_genesis_json_url: https://raw.githubusercontent.com/maticnetwork/launch/master/mainnet-v1/sentry/sentry/heimdall/config/genesis.json

heimdall_max_open_connections: 100

bor_dir: "{{ data_dir }}/.bor"

# <bor_version> is the bor release version.
# See https://github.com/maticnetwork/bor/releases/
bor_version: v0.2.14

bor_bootnodes: "enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303,enode://3178257cd1e1ab8f95eeb7cc45e28b6047a0432b2f9412cff1db9bb31426eac30edeb81fedc30b7cd3059f0902b5350f75d1b376d2c632e1b375af0553813e6f@35.221.13.28:30303,enode://16d9a28eadbd247a09ff53b7b1f22231f6deaf10b86d4b23924023aea49bfdd51465b36d79d29be46a5497a96151a1a1ea448f8a8666266284e004306b2afb6e@35.199.4.13:30303,enode://ef271e1c28382daa6ac2d1006dd1924356cfd843dbe88a7397d53396e0741ca1a8da0a113913dee52d9071f0ad8d39e3ce87aa81ebc190776432ee7ddc9d9470@35.230.116.151:30303"

bor_daemon_name: bor

bor_genesis_json_url: https://raw.githubusercontent.com/maticnetwork/launch/master/mainnet-v1/sentry/sentry/bor/genesis.json

# <bor_extra_run_args> is an optinal extra flags
bor_extra_run_args: "--ipcdisable"

# <golang_bin_dir> is the location of the golang bin folder which will be added
# to the $PATH.
golang_bin_dir: /usr/local/go/bin

eth_rpc_url: ""

# <alidator_address> is reserved for future to setup Sentry nodes.
validator_address: ""

network_id: 137

bor_config: {}

default_bor_config:
  Eth:
    SyncMode: "full"
    NetworkId: "{{ network_id }}"
  Node:
    DataDir: "{{ bor_dir }}/data"
    KeyStoreDir: "{{ bor_dir }}/keystore"
    HTTPHost: "0.0.0.0"
    HTTPPort: 8545
    HTTPCors:
      - "*"
    HTTPVirtualHosts:
      - "*"
    HTTPModules:
      - eth
      - net
      - web3
      - bor
  Node.P2P:
    MaxPeers: 200
  Metrics:
    Enabled: false
    HTTP: "0.0.0.0"
    Port: 6060
